version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./app/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=Goth-todo
      - POSTGRES_PASSWORD=Gamer
      - POSTGRES_DB=todo
