CREATE TABLE tasks (
  id UUID PRIMARY KEY,
  userid UUID NOT NULL,
  FOREIGN KEY(userid) REFERENCES users (id),
  title VARCHAR(32) NOT NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  due_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);
